#!/bin/bash

#PBS -N hyperparam
#PBS -l select=1:ncpus=8:mem=64gb:ngpus=1
#PBS -l walltime=10:00:00
#PBS -j oe
#PBS -P personal-nady0006
#PBS -q normal

module load cuda/11.8.0
module load miniforge3/23.10

# Set the working directory to the root of your project
cd /home/users/ntu/nady0006/scratch/SC4001/Assignment2
conda init
conda activate /home/users/ntu/nady0006/scratch/SC4001/Assignment2/env

# Run the Python script
python finetune/finetune_hf_og.py
